In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'../data/raw/ai_adoption_dataset.csv')
df.head(25)

,country,industry,ai_tool,adoption_rate,daily_active_users,year,user_feedback,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,YyvLXOFyevRMSvJtkXodLvgejiqQNvSOZfeeJASDOVTxwm...,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,AdFVhenjthYSKJNzxzfaGQk wLnjRCgrHTyfXQEFjFJCMO...,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,zgNPmXBICRNbpjpTqIUWmMTeTYsInDNtAmzuxpDvcUZEAi...,45-54,Startup
3,UK,Manufacturing,ChatGPT,48.46,3488,2023,LxeKzQFbPvhxXUSgPVlLLJ pUFaicjCgiMtAmsTjovkrdE...,45-54,Enterprise
4,UK,Agriculture,Stable Diffusion,34.06,1124,2024,IOQtQoSKdSmiXRsUKpjXjXZgQohymFkVUvOASXlEnVsIOS...,45-54,SME
5,Brazil,Education,Midjourney,64.54,3267,2024,PDkHPYQGOo XqLNwpEsZlbubUVBUDBujoPCWEDoCtcwzKX...,55+,Startup
6,USA,Healthcare,Bard,81.83,4265,2023,VXo RcPqLBqywVUcwrpjmTha FxLtebijbOiZMEIYqkLEK...,35-44,Enterprise
7,Australia,Education,ChatGPT,20.85,5940,2023,MCVWNxfkdvijPwFleHKDKJTIexXAzweDWyBGDQVcOrfAsn...,25-34,Enterprise
8,China,Retail,Midjourney,39.90,613,2024,JJyYjvZPWunxapLpTfaampdgLFquyzjJELCEQfNnZLtXn...,55+,SME
9,USA,Agriculture,Midjourney,20.53,8310,2023,BmKCEuMhGTktndFlwMDIq UVbeFeqlnYXmRypfMgBwuG c...,35-44,Startup
10,Canada,Education,Midjourney,24.10,7182,2024,YdwlGHwJUqyHYwWldqeIPPGBUujdNGwDJJqrupkIPFnZHA...,55+,Startup
11,South Korea,Technology,Midjourney,58.21,4012,2024,WtChjszrtgAODj iiSWZnbulvnBtZTjPMBp UpzZvDbbxA...,18-24,SME
12,France,Manufacturing,Midjourney,92.16,8924,2023,VguhmVMseDEXoWEtHBLiCoBaWGxeQkBSOMFvahshPVPZti...,25-34,SME
13,France,Finance,ChatGPT,37.56,8903,2024,GjEUHVeLfVeGOzeoztyIeFKgkSEVNoUuDyXsMnqFsubNZZ...,55+,SME
14,France,Agriculture,Midjourney,48.32,9190,2024,NyMgsaemnvSuxLKVhJjnCiPDrIDfhopJuHxBDIdZnRd cL...,45-54,Startup
15,France,Education,ChatGPT,26.86,3331,2023,hpURqatsveuQXmxqsAmolTqk ipkAoAvEKn FemfDrclaC...,25-34,Startup
16,Canada,Manufacturing,Midjourney,9.50,2559,2024,uLLXJcnqBePfZBhGFoUPLuuUeTXDmeCONBCAoOOqJzKZa...,25-34,Startup
17,India,Agriculture,ChatGPT,59.62,2780,2024,ieKfyjY LrSreDCnxEuq FpDLyQzBjKLEbZUrneAYmSjLA...,35-44,Enterprise
18,Brazil,Manufacturing,ChatGPT,4.33,7327,2024,YAfOjIvRQukurbRlVMWGcerwrfMhvVqzvYQiXoYsQXElra...,25-34,Startup
19,UK,Education,Stable Diffusion,9.23,4662,2024,SacrBIdPkMoiuysNpTguwEjLgJsIGHsqXHAqkluQEVWveL...,25-34,SME
20,Canada,Finance,Midjourney,73.16,1549,2023,CrwYLrAaobMXJuStRzCWEblSVEoJxrvPIZDFvyGvLdAaVL...,18-24,Startup
21,Germany,Technology,Stable Diffusion,4.53,1692,2024,RrYlnOPHRiAKbmWqjOrYwfifV iKOEXAFlzN OPzdjNNAJ...,55+,Enterprise
22,India,Healthcare,Stable Diffusion,13.86,9872,2023,zrYduYaTgybWmTDnuXdQTKvPxbfOvlptqhgrlunUoTWgmb...,35-44,Startup
23,South Korea,Technology,ChatGPT,1.88,7488,2023,tAznjdcxDXWtxUHChMnVRKZoKRbOUNsgxrPeoEwilnVegZ...,55+,SME
24,France,Healthcare,ChatGPT,86.20,3956,2024,jkUZaGCEIKUrFAmfKAKBLZwczyRvqvbBvzylvFwqtnYBun...,45-54,Startup

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"../data/raw/MEC02.20260316203407.csv")
df.head()

,STATISTIC,Statistic Label,TLIST(Q1),Quarter,C03907V04659,Electricity Consumption,UNIT,VALUE
0,MEC02,Gigawatt hours,2015Q1,2015Q1,-,All metered electricity consumption,GWh,6565
1,MEC02,Gigawatt hours,2015Q1,2015Q1,10,Data centres,GWh,290
2,MEC02,Gigawatt hours,2015Q1,2015Q1,20,Customers other than data centres,GWh,6275
3,MEC02,Gigawatt hours,2015Q2,2015Q2,-,All metered electricity consumption,GWh,6086
4,MEC02,Gigawatt hours,2015Q2,2015Q2,10,Data centres,GWh,303

In [2]:
import pandas as pd

df = pd.read_csv(r"../data/raw/WEO2025_AnnexA_Free_Dataset_World.csv")
df.head()

,PUBLICATION,SCENARIO,CATEGORY,PRODUCT,FLOW,UNIT,REGION,YEAR,VALUE
0,World Energy Outlook 2025,Historical,Energy,Total,Total energy supply,EJ,World,2010,536.406
1,World Energy Outlook 2025,Historical,Energy,Total,Total energy supply,EJ,World,2023,640.738
2,World Energy Outlook 2025,Historical,Energy,Total,Total energy supply,EJ,World,2024,654.245
3,World Energy Outlook 2025,Current Policies Scenario,Energy,Total,Total energy supply,EJ,World,2035,744.085
4,World Energy Outlook 2025,Current Policies Scenario,Energy,Total,Total energy supply,EJ,World,2040,776.503