In [8]:
import pandas as pd 
import numpy as np

#leitura do arquivo csv / A.I csv
df = pd.read_csv('../data/raw/ai_adoption_dataset.csv')
df.head(3)

,country,industry,ai_tool,adoption_rate,daily_active_users,year,user_feedback,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,YyvLXOFyevRMSvJtkXodLvgejiqQNvSOZfeeJASDOVTxwm...,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,AdFVhenjthYSKJNzxzfaGQk wLnjRCgrHTyfXQEFjFJCMO...,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,zgNPmXBICRNbpjpTqIUWmMTeTYsInDNtAmzuxpDvcUZEAi...,45-54,Startup

In [9]:

#media adoção por ano
adocao = df.groupby("year")["adoption_rate"].mean().sort_index()
#diferença de um ano pro outro
tempo = adocao.diff()
print(tempo)
print(adocao)

year
2023         NaN
2024   -0.211962
Name: adoption_rate, dtype: float64
year
2023    50.022059
2024    49.810097
Name: adoption_rate, dtype: float64

In [10]:
#analise por pais
paisAnalise = df.groupby("country")["adoption_rate"].mean().sort_values(ascending=False)
print(paisAnalise)

country
Germany        50.179163
India          50.059208
Australia      49.991022
Brazil         49.987023
Canada         49.922906
South Korea    49.887389
UK             49.789302
France         49.785724
China          49.624838
USA            49.503073
Name: adoption_rate, dtype: float64

In [11]:
#ranking de setores
setor = df.groupby("industry")["adoption_rate"].mean().sort_values(ascending=False)
print(setor.head(10))

industry
Agriculture       50.329049
Technology        50.017133
Finance           49.960481
Healthcare        49.868791
Transportation    49.842929
Education         49.788982
Retail            49.607140
Manufacturing     49.575804
Name: adoption_rate, dtype: float64

In [12]:
#pais por setor 
paisSetor = df.pivot_table(
    values = "adoption_rate",
    index = "industry",
    columns = "country",
    aggfunc = "mean"
)

print(paisSetor)

country         Australia     Brazil     Canada      China     France  \
industry
Agriculture     49.868118  49.805014  49.538573  51.401234  50.801913
Education       49.670448  50.228730  49.673006  49.675482  49.903614
Finance         50.372199  50.912366  49.756445  49.171850  49.788796
Healthcare      50.316913  49.364489  49.363784  49.880782  49.306187
Manufacturing   50.550195  49.575323  50.577037  49.717245  49.083480
Retail          48.872760  49.430752  49.715220  49.244822  49.620394
Technology      50.252685  51.157447  50.145538  48.399281  49.794844
Transportation  50.049854  49.362225  50.617750  49.527137  50.040941

country           Germany      India  South Korea         UK        USA
industry
Agriculture     50.569821  50.932527    50.559287  49.899184  49.961879
Education       49.572518  49.797531    49.371145  50.414145  49.604809
Finance         50.636569  49.939473    49.688724  50.172426  49.192160
Healthcare      51.594473  50.600459    50.132282  49.371705  48.857886
Manufacturing   50.261548  49.320939    50.035205  48.039631  48.568338
Retail          50.052662  50.167088    49.826244  49.939670  49.221568
Technology      50.206399  49.351848    50.054232  49.728637  51.028526
Transportation  48.536015  50.457489    49.451248  50.757712  49.599301

In [13]:
import pandas as pd
import numpy as np

#leitura do arquivo csv de consumo de energia / csv eletricity consumption
df = pd.read_csv(r"../data/raw/MEC02.20260316203407.csv")
df.tail(3)

,STATISTIC,Statistic Label,TLIST(Q1),Quarter,C03907V04659,Electricity Consumption,UNIT,VALUE
117,MEC02,Gigawatt hours,2024Q4,2024Q4,-,All metered electricity consumption,GWh,8109
118,MEC02,Gigawatt hours,2024Q4,2024Q4,10,Data centres,GWh,1829
119,MEC02,Gigawatt hours,2024Q4,2024Q4,20,Customers other than data centres,GWh,6280

In [14]:
#consumo ao longo do tempo
consumoTempo = df.groupby("TLIST(Q1)")["VALUE"].mean()
print(consumoTempo)

TLIST(Q1)
2015Q1    4376.666667
2015Q2    4057.333333
2015Q3    3855.666667
2015Q4    4110.333333
2016Q1    4434.000000
2016Q2    4314.000000
2016Q3    3950.666667
2016Q4    4205.000000
2017Q1    4578.000000
2017Q2    4286.000000
2017Q3    3979.000000
2017Q4    4307.333333
2018Q1    4731.333333
2018Q2    4563.000000
2018Q3    4124.666667
2018Q4    4401.000000
2019Q1    4752.000000
2019Q2    4232.666667
2019Q3    4199.666667
2019Q4    4485.333333
2020Q1    4932.333333
2020Q2    4286.000000
2020Q3    4253.666667
2020Q4    4564.666667
2021Q1    4898.000000
2021Q2    4814.333333
2021Q3    4519.666667
2021Q4    4772.000000
2022Q1    5231.333333
2022Q2    5016.000000
2022Q3    4700.000000
2022Q4    4936.333333
2023Q1    5358.666667
2023Q2    5137.333333
2023Q3    4757.333333
2023Q4    5134.000000
2024Q1    5564.666667
2024Q2    5290.000000
2024Q3    5008.333333
2024Q4    5406.000000
Name: VALUE, dtype: float64

In [15]:
# percentual do consumo de data centres ao loongo dos anos e dos valores
df_dc = df[df["Electricity Consumption"] == "Data centres"]
df_dc = df_dc.sort_values("TLIST(Q1)")
df_dc["growth"] = df_dc["VALUE"].pct_change()
print(df_dc[["TLIST(Q1)", "VALUE", "growth"]])

    TLIST(Q1)  VALUE    growth
1      2015Q1    290       NaN
4      2015Q2    303  0.044828
7      2015Q3    316  0.042904
10     2015Q4    329  0.041139
13     2016Q1    340  0.033435
16     2016Q2    360  0.058824
19     2016Q3    385  0.069444
22     2016Q4    395  0.025974
25     2017Q1    406  0.027848
28     2017Q2    433  0.066502
31     2017Q3    449  0.036952
34     2017Q4    472  0.051225
37     2018Q1    490  0.038136
40     2018Q2    526  0.073469
43     2018Q3    573  0.089354
46     2018Q4    591  0.031414
49     2019Q1    578 -0.021997
52     2019Q2    600  0.038062
55     2019Q3    638  0.063333
58     2019Q4    672  0.053292
61     2020Q1    690  0.026786
64     2020Q2    721  0.044928
67     2020Q3    765  0.061026
70     2020Q4    851  0.112418
73     2021Q1    921  0.082256
76     2021Q2    986  0.070575
79     2021Q3   1035  0.049696
82     2021Q4   1068  0.031884
85     2022Q1   1194  0.117978
88     2022Q2   1286  0.077052
91     2022Q3   1335  0.038103
94     2022Q4   1456  0.090637
97     2023Q1   1496  0.027473
100    2023Q2   1553  0.038102
103    2023Q3   1625  0.046362
106    2023Q4   1662  0.022769
109    2024Q1   1657 -0.003008
112    2024Q2   1691  0.020519
115    2024Q3   1792  0.059728
118    2024Q4   1829  0.020647

In [19]:
#consumo por categoria
dfCategoria = df[df["Electricity Consumption"] == "Data centres"]
consumoCategoria = dfCategoria.groupby("TLIST(Q1)")["VALUE"].mean().reset_index()
print(consumoCategoria)

   TLIST(Q1)   VALUE
0     2015Q1   290.0
1     2015Q2   303.0
2     2015Q3   316.0
3     2015Q4   329.0
4     2016Q1   340.0
5     2016Q2   360.0
6     2016Q3   385.0
7     2016Q4   395.0
8     2017Q1   406.0
9     2017Q2   433.0
10    2017Q3   449.0
11    2017Q4   472.0
12    2018Q1   490.0
13    2018Q2   526.0
14    2018Q3   573.0
15    2018Q4   591.0
16    2019Q1   578.0
17    2019Q2   600.0
18    2019Q3   638.0
19    2019Q4   672.0
20    2020Q1   690.0
21    2020Q2   721.0
22    2020Q3   765.0
23    2020Q4   851.0
24    2021Q1   921.0
25    2021Q2   986.0
26    2021Q3  1035.0
27    2021Q4  1068.0
28    2022Q1  1194.0
29    2022Q2  1286.0
30    2022Q3  1335.0
31    2022Q4  1456.0
32    2023Q1  1496.0
33    2023Q2  1553.0
34    2023Q3  1625.0
35    2023Q4  1662.0
36    2024Q1  1657.0
37    2024Q2  1691.0
38    2024Q3  1792.0
39    2024Q4  1829.0

In [25]:
consumoCategoria = dfCategoria.groupby("TLIST(Q1)")["VALUE"].mean().reset_index()
consumoCategoria.to_csv("../data/processed/dataset_cedt.csv", index=False)

In [26]:
import pandas as pd

#leitura arquivo csv de cinsumo energico em escala global e preditiva
df = pd.read_csv(r"../data/raw/WEO2025_AnnexA_Free_Dataset_World.csv")
df.head(3)

,PUBLICATION,SCENARIO,CATEGORY,PRODUCT,FLOW,UNIT,REGION,YEAR,VALUE
0,World Energy Outlook 2025,Historical,Energy,Total,Total energy supply,EJ,World,2010,536.406
1,World Energy Outlook 2025,Historical,Energy,Total,Total energy supply,EJ,World,2023,640.738
2,World Energy Outlook 2025,Historical,Energy,Total,Total energy supply,EJ,World,2024,654.245

In [27]:
#consumo por ano
consumoAno = df.groupby("YEAR")["VALUE"].mean()
print(consumoAno)

YEAR
2010    3959.632902
2023    5307.921197
2024    5452.378824
2035    6549.333081
2040    7051.262945
2050    8115.951993
Name: VALUE, dtype: float64

In [28]:
#comporação por cenario e ano
df = df.sort_values("YEAR")
comparaçãoC = df.groupby(["SCENARIO", "YEAR"])["VALUE"].mean().reset_index()
comparaçãoC["growthC"] = comparaçãoC.groupby("SCENARIO")["VALUE"].pct_change()
print(comparaçãoC[["SCENARIO", "YEAR", "growthC"]])

                               SCENARIO  YEAR   growthC
0             Current Policies Scenario  2035       NaN
1             Current Policies Scenario  2040  0.086129
2             Current Policies Scenario  2050  0.152869
3                            Historical  2010       NaN
4                            Historical  2023  0.340508
5                            Historical  2024  0.027215
6   Net Zero Emissions by 2050 Scenario  2035       NaN
7   Net Zero Emissions by 2050 Scenario  2040  0.066206
8   Net Zero Emissions by 2050 Scenario  2050  0.156775
9              Stated Policies Scenario  2035       NaN
10             Stated Policies Scenario  2040  0.076633
11             Stated Policies Scenario  2050  0.143774

In [30]:
#df final 
df_final = comparaçãoC[["YEAR", "VALUE", "SCENARIO", "growthC"]]
df_final.to_csv("../data/processed/dataset_anosfuturos.csv", index=False)